[tool.poetry]
name = "florgon-cc-cli"
version = "0.12.0"
license = "MIT"
homepage = "https://cc.florgon.com/"
keywords = ["cli", "url shortener", "paste manager"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Utilities",
    "Typing :: Typed"
]
description = "CLI interface for https://cc.florgon.com/"
authors = ["Степан Зубков <zubkovbackend@gmail.com>"]
readme = "README.md"
packages = [{include = "florgon_cc_cli"}]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.1.3"
pick = "^2.2.0"
requests = "^2.28.2"
toml = "^0.10.2"
pygments = "^2.15.1"

[tool.poetry.scripts]
florgon-cc = "florgon_cc_cli.main:main"

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/legacy/"
priority = "primary"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
